kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # Optional: specify pod subnet to avoid conflicts
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
  - role: worker
  - role: worker
