apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: host-visible-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.19.0.240-172.19.0.250   # pick a free range inside manifest_files_default
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: host-visible-l2
  namespace: metallb-system