version: "3.8"

services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"   # Access at http://<host>:8000
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBNAME: ${POSTGRES_DB}
      PAPERLESS_DBUSER: ${POSTGRES_USER}
      PAPERLESS_DBPASS: ${POSTGRES_PASSWORD}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_WORKERS: 1
      USERMAP_UID: 1000
      USERMAP_GID: 1000
    volumes:
      - /srv/paperless/data:/usr/src/paperless/data
      - /srv/paperless/media:/usr/src/paperless/media
      - /srv/paperless/export:/usr/src/paperless/export
      - /srv/paperless/consume:/usr/src/paperless/consume

  db:
    image: postgres:15
    container_name: paperless-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /srv/paperless/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: paperless-redis
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - /srv/paperless/ollama:/root/.ollama

  paperless-ai:
    image: clusterzx/paperless-ai:latest
    container_name: paperless-ai
    restart: unless-stopped
    depends_on:
      - paperless-ngx
      - ollama
    environment:
      PAPERLESS_URL: http://paperless-ngx:8000
      PAPERLESS_API_TOKEN: ${PAPERLESS_API_TOKEN}
      PAPERLESS_AI_PROVIDER: ollama
      PAPERLESS_AI_OLLAMA_HOST: http://ollama:11434
      PAPERLESS_AI_OLLAMA_MODEL: phi3:3.8b-mini-4k-instruct-q4_K_M
      PAPERLESS_AI_REQUEST_TIMEOUT: 3600000
      PAPERLESS_AI_ANALYSIS_TIMEOUT: 3600000
      PROMPT_TAGS: ""
      RESTRICT_TO_EXISTING_TAGS: no
    volumes:
      - /srv/paperless/ai:/app/data
    ports:
      - "3001:3000"

volumes:
  data:
  media:
  export:
  consume:
  postgres:
  ai:
  ollama:
