version: '3.9'

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    command: hbbs -r 192.168.0.21:21117
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/root

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    command: hbbr
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/root
