apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm-db
  namespace: npm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npm-db
  template:
    metadata:
      labels:
        app: npm-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.5
        envFrom:
        - secretRef:
            name: npm-secrets
        - configMapRef:
            name: npm-config
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-storage
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: npm-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm-app
  namespace: npm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npm-app
  template:
    metadata:
      labels:
        app: npm-app
    spec:
      containers:
      - name: npm
        image: jc21/nginx-proxy-manager:latest
        envFrom:
        - secretRef:
            name: npm-secrets
        - configMapRef:
            name: npm-config
        ports:
        - containerPort: 80
        - containerPort: 81
        - containerPort: 443
        volumeMounts:
        - mountPath: /data
          name: app-data
        - mountPath: /etc/letsencrypt
          name: app-data
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: npm-data
