apiVersion: v1
kind: Service
metadata:
  name: npm-app
  namespace: npm
spec:
  type: NodePort
  selector:
    app: npm-app
  ports:
    - name: http
      port: 81
      targetPort: 81
      nodePort: 30081
    - name: http-proxy
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443